language: cpp
compiler:
- gcc
- clang
install:
- wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
- bii setup:cpp

before_script:
- bii -v
- cd ..
- bii init build && cd build
- bii new HaMster21/monex
- mv -f ../monex/ blocks/HaMster21

script:
- bii find --update
- bii cpp:configure
- bii cpp:build

notifications:
  slack:
    secure: Bag3TWz5uYGZjrM0Q2LwkaP0pUpd+PMTAKOvinWhCcD2ZnY7/kE1SMjMfl2+IOxt0JSde2TqYZhYP9ZJ+8dYGKvnsVeSocV5CyHRyo3gClDNVt4EAR4O1AOV756lRiUau2RE88On3wtXOqyYP9QuPLE5dw/dchEy6Jc8KDgag4Q=
