language: cpp
compiler:
- gcc
- clang
install:
- sudo apt-get install tree
- wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
- bii setup:cpp
before_script:
- tree
- bii -v
- cd ..
- bii init build && cd build
- bii new HaMster21/monex
- pwd && tree
- mv -f ../monex/ blocks/HaMster21
- pwd && tree

script:
- bii find --update
- bii cpp:configure
- pwd && tree
- bii cpp:build

notifications:
  slack:
    secure: Bag3TWz5uYGZjrM0Q2LwkaP0pUpd+PMTAKOvinWhCcD2ZnY7/kE1SMjMfl2+IOxt0JSde2TqYZhYP9ZJ+8dYGKvnsVeSocV5CyHRyo3gClDNVt4EAR4O1AOV756lRiUau2RE88On3wtXOqyYP9QuPLE5dw/dchEy6Jc8KDgag4Q=
