language: cpp

compiler:
    - gcc
    - clang

install:
    #Install biicode
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp

before_script:
  - bii -v
  - cd /tmp
  - bii init monex && cd monex
  - bii new HaMster21/monex && cd blocks/HaMster21/monex

script:
  - bii find --update
  - bii cpp:configure
  - bii cpp:build
